spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clientedb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
rabbitmq:
  host: localhost
  username: guest
  password: guest
